# Generated by Django 4.2.4 on 2023-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_message_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
